name: Store Deploy to surge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
    - uses: actions/checkout@v2
    
    - name: Install Node.js enviornment
      uses: actions/setup-node@v3.5.1
      with:
        version: 12
        
    - name: GitHub Action for Yarn
      # You may pin to the exact commit or the version.
      # uses: Borales/actions-yarn@fdf0082f8938ca4193f000342661784eb8e11f6a
      uses: Borales/actions-yarn@v3
      with:
        # Yarn command
        cmd: install  # npm install / yarn install
        
    - name: Creating React Build
      run: sudo yarn build
      
    - name: Install Surge
      run: npm i -g surge
      
    - name: Deploy to Surge
      run: surge ./build http://mateen-react-router-store.surge.sh/ --token ${{ secrets.STORE_TOKEN }}
